name: Auto-Merge PR on Approval

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Check PR Approval
        id: approval
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          REVIEWS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews")
          if echo "${REVIEWS}" | jq -e '.[] | select(.state == "APPROVED")' > /dev/null; then
             echo "PR is approved."
             echo "::set-output name=approved::true"
          else
             echo "PR is not approved."
             echo "::set-output name=approved::false"
          fi
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Merge PR
        if: steps.approval.outputs.approved == 'true'
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          RESPONSE=$(curl -s -X PUT -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/merge")
          echo "Merge response: $RESPONSE"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}