name: Auto-Merge PR on Approval

on:
  workflow_dispatch:
    inputs: 
      pr_request_number: 
        description: 'Enter Request Number'
        required: true
      repository: 
        description: 'Enter Repository'
        required: true

  # pull_request:  
  #   types:
  #     - opened
  #     - synchronize

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Input Parameters
        run: |
            echo "Request Number : ${{ inputs.pr_request_number }}"
            echo "Repository : ${{ inputs.repository }}"
            
      - name: Check PR Approval
        id: approval
        run: |
          PR_NUMBER="${{ inputs.pr_request_number }}"
          REPOSITORY=${{ inputs.repository }}
          REVIEWS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             "https://api.github.com/repos/${REPOSITORY}/pulls/${PR_NUMBER}/reviews")
          if echo "${REVIEWS}" | jq -e '.[] | select(.state == "APPROVED")' > /dev/null; then
             echo "PR is approved."
             echo "::set-output name=approved::true"
          else        
             echo "PR is not approved."
             echo "::set-output name=approved::false"
          fi
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Merge PR
        if: steps.approval.outputs.approved == 'true'
        run: |
          PR_NUMBER="${{ inputs.pr_request_number }}"
          RESPONSE=$(curl -s -X PUT -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${REPOSITORY}/pulls/${PR_NUMBER}/merge")
          echo "Merge response: $RESPONSE"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}